target 'SwiftEntryKitDemo' do
    platform :ios, '13.0'
    use_frameworks!
    pod 'SwiftEntryKit', :path => '../'
end

target 'SwiftEntryKitTests' do
    platform :ios, '13.0'
    use_frameworks!
    pod 'SwiftEntryKit', :path => '../'
end
